name: .NET Core Build and Test
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          **/*.lock.json
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: nuget-${{ runner.os }}-
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
 
    - name: Restore NuGet packages
      run: dotnet restore ./MyWebApp
 
    - name: Build and Test
      run: dotnet build --configuration Release ./MyWebApp && dotnet test ./MyWebApp
