name: Matrix Build and Test with cache 
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]
        runtime: [linux-x64, win10-x64, osx-x64]
 
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
 
    - name: Display OS, .NET Core Version, Configuration, and Runtime
      run: |
        echo "Running on: ${{ matrix.os }}"
        echo "Using .NET Core version 7.x"
        echo "Configuration: ${{ matrix.configuration }}"
        echo "Runtime: ${{ matrix.runtime }}"

    - name: Restore dependencies
      run: |
        cd MyWebApp
        dotnet restore
    - name: Cache .NET packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          ~/.local/share/NuGet/Cache
        key: dotnet-packages-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          dotnet-packages-${{ runner.os }}-

    - name: Build and Test
      run: |
        cd MyWebApp
        dotnet build --configuration ${{ matrix.configuration }} --runtime ${{ matrix.runtime }} --no-self-contained   
        dotnet test

    - name: Deploy
      id: deploy
      run: |
        if [ "${{ matrix.configuration }}" = "Release" ] && [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          echo "Deploying on Ubuntu for Release configuration"
          echo "Deploying"
          echo "::set-output name=deploy_success::true"
        else
          echo "Skipping deployment"
          echo "::set-output name=deploy_success::false"
        fi
      if: matrix.configuration == 'Release' && matrix.os == 'ubuntu-latest'
 
    - name: Send Email on Successful Deploy
      if: steps.deploy.outputs.deploy_success == 'true'
      uses: cinotify/github-action@main
      with:
        to: 'rajanparamesh@gmail.com' #enter an email address to which the notification needs to be sent
        subject: 'Deployment Successful'
        body: |
          Hey ${{github.actor}}! The deployment on ${{ matrix.os }} for configuration ${{ matrix.configuration }} and runtime ${{ matrix.runtime }} was successful.
