name: Use GitHub Workflow Variables
 
on:
  push:
    branches:
      - main
 
jobs:
  display-variables:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Display GitHub Workflow Variables
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Path: ${{ github.event_path }}"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Action: ${{ github.action }}"
          echo "Actor: ${{ github.actor }}"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Event JSON: ${{ toJson(github.event) }}"
